CREATE TABLE dbo.TBL_DIM_TIEMPO_T0 (
    SK_DIM_TIEMPO BIGINT NOT NULL,
    DT_FECHA_NOTIFICACION DATE NOT NULL,
    INT_DIA SMALLINT NULL,
    INT_MES SMALLINT NULL,
    INT_ANIO SMALLINT NULL,
    INT_PERIODO INT NULL,
    INT_SEMANA_MES SMALLINT NULL,
    STR_MES NVARCHAR(50) NULL,
    STR_SEMESTRE NVARCHAR(50) NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

-- VALOR DE PARÁMETROS TIPO STRING

/*
START_DATE = 2020-03-21
END_DATE = 2022-01-23
*/

-- VALOR DE EXPRESIÓN - VARIABLE TIPO STRING VAR_TBL_DIM_TIEMPO

/*
"DECLARE @START_DATE DATE = '"+ @[$Package::START_DATE] +"';DECLARE @END_DATE DATE = '"+ @[$Package::END_DATE] +"';INSERT INTO dbo.TBL_DIM_TIEMPO_T0 (
    SK_DIM_TIEMPO,
    DT_FECHA_NOTIFICACION,
    INT_DIA,
    INT_MES,
    INT_ANIO,
    INT_PERIODO,
    INT_SEMANA_MES,
    STR_MES,
    STR_SEMESTRE,
    DT_FECHA_CARGUE
)
SELECT
	-- SK_DIM_TIEMPO: Formato YYYYMMDD
    FORMAT(FECHA, 'yyyyMMdd') AS SK_DIM_TIEMPO,

	-- DT_FECHA: FECHA
    FECHA AS DT_FECHA_NOTIFICACION,

	-- INT_DIA: DÍA
    DAY(FECHA) AS INT_DIA,

	-- INT_MES: NÚMERO DEL MES
    MONTH(FECHA) AS INT_MES,

	-- INT_ANIO: AÑO
    YEAR(FECHA) AS INT_ANIO,

	-- INT_PERIODO: TRIMESTRE
    FORMAT(FECHA, 'yyyyMM') AS INT_PERIODO,

	-- INT_SEMANA_MES: SEMANA DEL MES
    CASE 
        WHEN DAY(FECHA) <= 7 THEN 1
        WHEN DAY(FECHA) <= 14 THEN 2
        WHEN DAY(FECHA) <= 21 THEN 3
        WHEN DAY(FECHA) <= 28 THEN 4
        ELSE 5
    END AS INT_SEMANA_MES,

	-- STR_MES: MES
    CASE MONTH(FECHA)
        WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO'
        WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO'
        WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SEPTIEMBRE'
        WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' ELSE 'DICIEMBRE'
    END AS STR_MES,

	-- STR_SEMESTRE: SEMESTRE
    CASE WHEN MONTH(FECHA) <= 6 THEN '1ER SEMESTRE' ELSE '2DO SEMESTRE' END AS STR_SEMESTRE,

	-- DT_FECHA_CARGUE (FECHA/HORA ACTUAL)
    GETDATE() AS DT_FECHA_CARGUE

FROM (
    -- GENERAR FECHAS ENTRE START_DATE Y END_DATE
    SELECT DATEADD(DAY, NUMBER, @START_DATE) AS FECHA
    FROM master.dbo.spt_values
    WHERE type = 'P' 
    AND NUMBER <= DATEDIFF(DAY, @START_DATE, @END_DATE)
) AS FECHAS

WHERE NOT EXISTS (
    -- EVITAR DUPLICADOS
    SELECT 1 FROM dbo.TBL_DIM_TIEMPO_T0 T 
    WHERE T.DT_FECHA_NOTIFICACION = FECHAS.FECHA
);"
*/

-- VERIFICAR REGISTROS

SELECT *
FROM dbo.TBL_DIM_TIEMPO_T0;

--------------------------------------

CREATE TABLE dbo.TBL_DIM_UBICACION_T0 (
    SK_DIM_UBICACION INT IDENTITY(1,1) PRIMARY KEY,
    STR_DEPARTAMENTO NVARCHAR(50) NOT NULL,
    STR_MUNICIPIO NVARCHAR(50) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

-- TEXTO COMANDO SQL - ORIGEN DE OLE DB

SELECT DISTINCT NOMBRE_DEPARTAMENTO ,NOMBRE_MUNICIPIO
FROM  dbo.TBL_CASOS_POSITIVOS;

-- USAR RESULTADO DE CONSULTA SQL - LOOKUP

SELECT SK_DIM_UBICACION, CONCAT(STR_DEPARTAMENTO, STR_MUNICIPIO) LLAVE_INSERT_D
FROM dbo.TBL_DIM_UBICACION_T0;

-- VERIFICAR REGISTROS

SELECT *
FROM dbo.TBL_DIM_UBICACION_T0;

--------------------------------------

CREATE TABLE dbo.TBL_DIM_PERSONA_T0 (
    SK_DIM_PERSONA INT IDENTITY(1,1) PRIMARY KEY,
    INT_EDAD TINYINT NOT NULL,
    STR_CATEGORIA_EDAD NVARCHAR(50) NOT NULL,
    CHR_SEXO NCHAR(10) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

-- TEXTO COMANDO SQL - ORIGEN DE OLE DB

SELECT DISTINCT 
    EDAD,
    CASE
        WHEN EDAD BETWEEN 1 AND 5 THEN 'PRIMERA INFANCIA (1–5)'
        WHEN EDAD BETWEEN 6 AND 11 THEN 'INFANCIA INTERMEDIA (6–11)'
        WHEN EDAD BETWEEN 12 AND 14 THEN 'ADOLESCENCIA TEMPRANA (12–14)'
        WHEN EDAD BETWEEN 15 AND 17 THEN 'ADOLESCENCIA MEDIA (15–17)'
        WHEN EDAD BETWEEN 18 AND 20 THEN 'ADOLESCENCIA TARDÍA (18–20)'
        WHEN EDAD BETWEEN 21 AND 24 THEN 'ADULTEZ EMERGENTE (21–24)'
        WHEN EDAD BETWEEN 25 AND 39 THEN 'ADULTEZ JOVEN (25–39)'
        WHEN EDAD BETWEEN 40 AND 54 THEN 'ADULTEZ MEDIA (40–54)'
        WHEN EDAD BETWEEN 55 AND 64 THEN 'ADULTEZ MEDIA TARDÍA (55–64)'
        WHEN EDAD BETWEEN 65 AND 74 THEN 'ADULTEZ MAYOR TEMPRANA (65–74)'
        WHEN EDAD BETWEEN 75 AND 84 THEN 'ADULTEZ MAYOR (75–84)'
        WHEN EDAD BETWEEN 85 AND 94 THEN 'VEJEZ AVANZADA (85–94)'
        WHEN EDAD BETWEEN 95 AND 113 THEN 'LONGEVIDAD EXTREMA (95–113)'
        ELSE 'FUERA DE RANGO'
    END AS CATEGORIA_EDAD,
	SEXO
FROM dbo.TBL_CASOS_POSITIVOS
ORDER BY EDAD;

-- USAR RESULTADO DE CONSULTA SQL - LOOKUP

SELECT SK_DIM_PERSONA, CONCAT(INT_EDAD, STR_CATEGORIA_EDAD, CHR_SEXO) LLAVE_INSERT_D
FROM dbo.TBL_DIM_PERSONA_T0;

-- VERIFICAR REGISTROS

SELECT * 
FROM dbo.TBL_DIM_PERSONA_T0;

--------------------------------------

CREATE TABLE dbo.TBL_DIM_CASO_T2 (
    SK_DIM_CASO INT IDENTITY(1,1) PRIMARY KEY,
    FLT_ID_CASO FLOAT NOT NULL,
    STR_TIPO_CONTAGIO NVARCHAR(50) NOT NULL,
    STR_UBICACION_CASO NVARCHAR(50) NOT NULL,
    STR_ESTADO NVARCHAR(50) NOT NULL,
    STR_CONDICION_FINAL NVARCHAR(50) NOT NULL,
    STR_TIPO_RECUPERACION NVARCHAR(50) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL,
    DT_FECHA_INICIO DATETIME NULL,
    DT_FECHA_VIGENCIA DATETIME NULL,
    INT_FLAG TINYINT NULL
);

--------------------------------------

CREATE TABLE dbo.TBL_FACT_CASOS (
    SK_DIM_CASO INT NULL,
    SK_DIM_PERSONA INT NULL,
    SK_DIM_UBICACION INT NULL,
    SK_DIM_TIEMPO INT NULL,
    BIT_IS_DEATH BIT NULL,
    INT_DAYS_TO_RECOVERY INT NULL,
    DT_FECHA_REPORTE_WEB DATETIME2(7) NULL,
    DT_FECHA_INICIO_SINTOMAS DATETIME2(7) NULL,
    DT_FECHA_MUERTE DATETIME2(7) NULL,
    DT_FECHA_DIAGNOSTICO DATETIME2(7) NULL,
    DT_FECHA_RECUPERACION DATETIME2(7) NULL,
    DT_FECHA_CARGUE DATETIME NULL
);