CREATE TABLE dbo.TBL_DIM_TIEMPO_T0 (
    SK_DIM_TIEMPO INT IDENTITY(1,1) PRIMARY KEY,
    DT_FECHA_NOTIFICACION DATETIME2(7) NOT NULL,
    INT_DIA SMALLINT NULL,
    INT_MES SMALLINT NULL,
    INT_ANIO SMALLINT NULL,
    INT_PERIODO SMALLINT NULL,
    INT_SEMANA_MES SMALLINT NULL,
    STR_MES NVARCHAR(50) NULL,
    STR_SEMESTRE NVARCHAR(50) NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

CREATE TABLE dbo.TBL_DIM_UBICACION_T0 (
    SK_DIM_UBICACION INT IDENTITY(1,1) PRIMARY KEY,
    STR_DEPARTAMENTO NVARCHAR(50) NOT NULL,
    STR_MUNICIPIO NVARCHAR(50) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

SELECT DISTINCT NOMBRE_DEPARTAMENTO ,NOMBRE_MUNICIPIO
FROM  dbo.TBL_CASOS_POSITIVOS;

SELECT SK_DIM_UBICACION, CONCAT(STR_DEPARTAMENTO, STR_MUNICIPIO) LLAVE_INSERT_D
FROM dbo.TBL_DIM_UBICACION_T0;

SELECT *
FROM dbo.TBL_DIM_UBICACION_T0;

CREATE TABLE dbo.TBL_DIM_PERSONA_T1 (
    SK_DIM_PERSONA INT IDENTITY(1,1) PRIMARY KEY,
    INT_EDAD TINYINT NOT NULL,
    STR_CATEGORIA_EDAD NVARCHAR(50) NOT NULL,
    CHR_SEXO NCHAR(10) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

CREATE TABLE dbo.TBL_DIM_CASO_T2 (
    SK_DIM_CASO INT IDENTITY(1,1) PRIMARY KEY,
    FLT_ID_CASO FLOAT NOT NULL,
    STR_TIPO_CONTAGIO NVARCHAR(50) NOT NULL,
    STR_UBICACION_CASO NVARCHAR(50) NOT NULL,
    STR_ESTADO NVARCHAR(50) NOT NULL,
    STR_CONDICION_FINAL NVARCHAR(50) NOT NULL,
    STR_TIPO_RECUPERACION NVARCHAR(50) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL,
    DT_FECHA_INICIO DATETIME NULL,
    DT_FECHA_VIGENCIA DATETIME NULL,
    INT_FLAG TINYINT NULL
);

CREATE TABLE dbo.TBL_FACT_CASOS (
    SK_DIM_CASO INT NULL,
    SK_DIM_PERSONA INT NULL,
    SK_DIM_UBICACION INT NULL,
    SK_DIM_TIEMPO INT NULL,
    BIT_IS_DEATH BIT NULL,
    INT_DAYS_TO_RECOVERY INT NULL,
    DT_FECHA_REPORTE_WEB DATETIME2(7) NULL,
    DT_FECHA_INICIO_SINTOMAS DATETIME2(7) NULL,
    DT_FECHA_MUERTE DATETIME2(7) NULL,
    DT_FECHA_DIAGNOSTICO DATETIME2(7) NULL,
    DT_FECHA_RECUPERACION DATETIME2(7) NULL,
    DT_FECHA_CARGUE DATETIME NULL
);