CREATE TABLE dbo.TBL_DIM_TIEMPO_T0 (
    SK_DIM_TIEMPO BIGINT NOT NULL,
    DT_FECHA_NOTIFICACION DATETIME2(7) NOT NULL,
    INT_DIA SMALLINT NULL,
    INT_MES SMALLINT NULL,
    INT_ANIO SMALLINT NULL,
    INT_PERIODO INT NULL,
    INT_SEMANA_MES SMALLINT NULL,
    STR_MES NVARCHAR(50) NULL,
    STR_SEMESTRE NVARCHAR(50) NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

DECLARE @START_DATE DATE = '2020-03-21';
DECLARE @END_DATE DATE = '2022-01-23';

INSERT INTO dbo.TBL_DIM_TIEMPO_T0 (
    SK_DIM_TIEMPO,
    DT_FECHA_NOTIFICACION,
    INT_DIA,
    INT_MES,
    INT_ANIO,
    INT_PERIODO,
    INT_SEMANA_MES,
    STR_MES,
    STR_SEMESTRE,
    DT_FECHA_CARGUE
)
SELECT
	-- SK_DIM_TIEMPO: Formato YYYYMMDD
    FORMAT(FECHA, 'yyyyMMdd') AS SK_DIM_TIEMPO,

	-- DT_FECHA: FECHA
    FECHA AS DT_FECHA_NOTIFICACION,

	-- INT_DIA: Día
    DAY(FECHA) AS INT_DIA,

	-- INT_MES: Número del mes
    MONTH(FECHA) AS INT_MES,

	-- INT_ANIO: Año
    YEAR(FECHA) AS INT_ANIO,

	-- INT_PERIODO: Trimestre
    FORMAT(FECHA, 'yyyyMM') AS INT_PERIODO,

	-- INT_SEMANA_MES: Semana del mes
    CASE 
        WHEN DAY(FECHA) <= 7 THEN 1
        WHEN DAY(FECHA) <= 14 THEN 2
        WHEN DAY(FECHA) <= 21 THEN 3
        WHEN DAY(FECHA) <= 28 THEN 4
        ELSE 5
    END AS INT_SEMANA_MES,

	-- STR_MES: Mes
    CASE MONTH(FECHA)
        WHEN 1 THEN 'Enero' WHEN 2 THEN 'Febrero' WHEN 3 THEN 'Marzo'
        WHEN 4 THEN 'Abril' WHEN 5 THEN 'Mayo' WHEN 6 THEN 'Junio'
        WHEN 7 THEN 'Julio' WHEN 8 THEN 'Agosto' WHEN 9 THEN 'Septiembre'
        WHEN 10 THEN 'Octubre' WHEN 11 THEN 'Noviembre' ELSE 'Diciembre'
    END AS STR_MES,

	-- STR_SEMESTRE: Semestre
    CASE WHEN MONTH(FECHA) <= 6 THEN '1er Semestre' ELSE '2do Semestre' END AS STR_SEMESTRE,

	-- DT_FECHA_CARGUE (fecha/hora actual)
    GETDATE() AS DT_FECHA_CARGUE

FROM (
    -- Generar FECHAS entre START_DATE y END_DATE
    SELECT DATEADD(DAY, NUMBER, @START_DATE) AS FECHA
    FROM master.dbo.spt_values
    WHERE type = 'P' 
    AND NUMBER <= DATEDIFF(DAY, @START_DATE, @END_DATE)
) AS FECHAS

WHERE NOT EXISTS (
    -- Evitar duplicados
    SELECT 1 FROM dbo.TBL_DIM_TIEMPO_T0 T 
    WHERE T.DT_FECHA_NOTIFICACION = FECHAS.FECHA
);

-- Expresión

/*
"DECLARE @START_DATE DATE = '"+ @[$Package::START_DATE] +"';DECLARE @END_DATE DATE = '"+ @[$Package::END_DATE] +"';INSERT INTO dbo.TBL_DIM_TIEMPO_T0 (
    SK_DIM_TIEMPO,
    DT_FECHA_NOTIFICACION,
    INT_DIA,
    INT_MES,
    INT_ANIO,
    INT_PERIODO,
    INT_SEMANA_MES,
    STR_MES,
    STR_SEMESTRE,
    DT_FECHA_CARGUE
)
SELECT
	-- SK_DIM_TIEMPO: Formato YYYYMMDD
    FORMAT(FECHA, 'yyyyMMdd') AS SK_DIM_TIEMPO,

	-- DT_FECHA: FECHA
    FECHA AS DT_FECHA_NOTIFICACION,

	-- INT_DIA: Día
    DAY(FECHA) AS INT_DIA,

	-- INT_MES: Número del mes
    MONTH(FECHA) AS INT_MES,

	-- INT_ANIO: Año
    YEAR(FECHA) AS INT_ANIO,

	-- INT_PERIODO: Trimestre
    FORMAT(FECHA, 'yyyyMM') AS INT_PERIODO,

	-- INT_SEMANA_MES: Semana del mes
    CASE 
        WHEN DAY(FECHA) <= 7 THEN 1
        WHEN DAY(FECHA) <= 14 THEN 2
        WHEN DAY(FECHA) <= 21 THEN 3
        WHEN DAY(FECHA) <= 28 THEN 4
        ELSE 5
    END AS INT_SEMANA_MES,

	-- STR_MES: Mes
    CASE MONTH(FECHA)
        WHEN 1 THEN 'Enero' WHEN 2 THEN 'Febrero' WHEN 3 THEN 'Marzo'
        WHEN 4 THEN 'Abril' WHEN 5 THEN 'Mayo' WHEN 6 THEN 'Junio'
        WHEN 7 THEN 'Julio' WHEN 8 THEN 'Agosto' WHEN 9 THEN 'Septiembre'
        WHEN 10 THEN 'Octubre' WHEN 11 THEN 'Noviembre' ELSE 'Diciembre'
    END AS STR_MES,

	-- STR_SEMESTRE: Semestre
    CASE WHEN MONTH(FECHA) <= 6 THEN '1er Semestre' ELSE '2do Semestre' END AS STR_SEMESTRE,

	-- DT_FECHA_CARGUE (fecha/hora actual)
    GETDATE() AS DT_FECHA_CARGUE

FROM (
    -- Generar FECHAS entre START_DATE y END_DATE
    SELECT DATEADD(DAY, NUMBER, @START_DATE) AS FECHA
    FROM master.dbo.spt_values
    WHERE type = 'P' 
    AND NUMBER <= DATEDIFF(DAY, @START_DATE, @END_DATE)
) AS FECHAS

WHERE NOT EXISTS (
    -- Evitar duplicados
    SELECT 1 FROM dbo.TBL_DIM_TIEMPO_T0 T 
    WHERE T.DT_FECHA_NOTIFICACION = FECHAS.FECHA
);"
*/

--------------------------------------

CREATE TABLE dbo.TBL_DIM_UBICACION_T0 (
    SK_DIM_UBICACION INT IDENTITY(1,1) PRIMARY KEY,
    STR_DEPARTAMENTO NVARCHAR(50) NOT NULL,
    STR_MUNICIPIO NVARCHAR(50) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

SELECT DISTINCT NOMBRE_DEPARTAMENTO ,NOMBRE_MUNICIPIO
FROM  dbo.TBL_CASOS_POSITIVOS;

SELECT SK_DIM_UBICACION, CONCAT(STR_DEPARTAMENTO, STR_MUNICIPIO) LLAVE_INSERT_D
FROM dbo.TBL_DIM_UBICACION_T0;

SELECT *
FROM dbo.TBL_DIM_UBICACION_T0;

--------------------------------------

CREATE TABLE dbo.TBL_DIM_PERSONA_T1 (
    SK_DIM_PERSONA INT IDENTITY(1,1) PRIMARY KEY,
    INT_EDAD TINYINT NOT NULL,
    STR_CATEGORIA_EDAD NVARCHAR(50) NOT NULL,
    CHR_SEXO NCHAR(10) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL
);

--------------------------------------

CREATE TABLE dbo.TBL_DIM_CASO_T2 (
    SK_DIM_CASO INT IDENTITY(1,1) PRIMARY KEY,
    FLT_ID_CASO FLOAT NOT NULL,
    STR_TIPO_CONTAGIO NVARCHAR(50) NOT NULL,
    STR_UBICACION_CASO NVARCHAR(50) NOT NULL,
    STR_ESTADO NVARCHAR(50) NOT NULL,
    STR_CONDICION_FINAL NVARCHAR(50) NOT NULL,
    STR_TIPO_RECUPERACION NVARCHAR(50) NOT NULL,
    DT_FECHA_CARGUE DATETIME NULL,
    DT_FECHA_INICIO DATETIME NULL,
    DT_FECHA_VIGENCIA DATETIME NULL,
    INT_FLAG TINYINT NULL
);

--------------------------------------

CREATE TABLE dbo.TBL_FACT_CASOS (
    SK_DIM_CASO INT NULL,
    SK_DIM_PERSONA INT NULL,
    SK_DIM_UBICACION INT NULL,
    SK_DIM_TIEMPO INT NULL,
    BIT_IS_DEATH BIT NULL,
    INT_DAYS_TO_RECOVERY INT NULL,
    DT_FECHA_REPORTE_WEB DATETIME2(7) NULL,
    DT_FECHA_INICIO_SINTOMAS DATETIME2(7) NULL,
    DT_FECHA_MUERTE DATETIME2(7) NULL,
    DT_FECHA_DIAGNOSTICO DATETIME2(7) NULL,
    DT_FECHA_RECUPERACION DATETIME2(7) NULL,
    DT_FECHA_CARGUE DATETIME NULL
);