{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "es-CO",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/VIVOBOOK-15\\SQLSERVER;DWH_COVID_19_COLOMBIA",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "VIVOBOOK-15\\SQLSERVER",
            "database": "DWH_COVID_19_COLOMBIA"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "vivobook-15\\sqlserver;DWH_COVID_19_COLOMBIA",
          "Username": "COVID_19_COL",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "TBL_DIM_CASO_T2",
        "columns": [
          {
            "name": "SK_DIM_CASO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_CASO"
          },
          {
            "name": "INT_ID_CASO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_ID_CASO"
          },
          {
            "name": "STR_TIPO_CONTAGIO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_TIPO_CONTAGIO"
          },
          {
            "name": "STR_UBICACION_CASO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_UBICACION_CASO"
          },
          {
            "name": "STR_ESTADO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_ESTADO"
          },
          {
            "name": "STR_CONDICION_FINAL",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_CONDICION_FINAL"
          },
          {
            "name": "STR_TIPO_RECUPERACION",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_TIPO_RECUPERACION"
          },
          {
            "name": "INT_FLAG",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_FLAG"
          },
          {
            "name": "DT_FECHA_REPORTE_WEB",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DT_FECHA_REPORTE_WEB"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/VIVOBOOK-15\\SQLSERVER;DWH_COVID_19_COLOMBIA\",",
                "    dbo_TBL_DIM_CASO_T2 = Source{[Schema=\"dbo\",Item=\"TBL_DIM_CASO_T2\"]}[Data],",
                "    #\"Uppercased Text\" = Table.TransformColumns(dbo_TBL_DIM_CASO_T2,{{\"STR_TIPO_CONTAGIO\", Text.Upper, type text}, {\"STR_UBICACION_CASO\", Text.Upper, type text}, {\"STR_ESTADO\", Text.Upper, type text}, {\"STR_CONDICION_FINAL\", Text.Upper, type text}, {\"STR_TIPO_RECUPERACION\", Text.Upper, type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Uppercased Text\",{\"DT_FECHA_CARGUE\", \"DT_FECHA_INICIO\", \"DT_FECHA_VIGENCIA\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Removed Columns\",{{\"STR_TIPO_CONTAGIO\", Text.Proper, type text}, {\"STR_UBICACION_CASO\", Text.Proper, type text}, {\"STR_ESTADO\", Text.Proper, type text}, {\"STR_CONDICION_FINAL\", Text.Proper, type text}, {\"STR_TIPO_RECUPERACION\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CASO",
            "levels": [
              {
                "name": "Tipo de Contagio",
                "ordinal": 1,
                "column": "STR_TIPO_CONTAGIO"
              },
              {
                "name": "Ubicación de Caso",
                "ordinal": 2,
                "column": "STR_UBICACION_CASO"
              },
              {
                "name": "Estado",
                "ordinal": 3,
                "column": "STR_ESTADO"
              },
              {
                "name": "Condición Final",
                "ordinal": 4,
                "column": "STR_CONDICION_FINAL"
              },
              {
                "name": "Tipo de Recuperación",
                "ordinal": 5,
                "column": "STR_TIPO_RECUPERACION"
              },
              {
                "name": "ID de Caso",
                "ordinal": 0,
                "column": "INT_ID_CASO"
              },
              {
                "name": "Bandera de Caso Actualizado",
                "ordinal": 6,
                "column": "INT_FLAG"
              }
            ]
          }
        ]
      },
      {
        "name": "TBL_DIM_PERSONA_T0",
        "columns": [
          {
            "name": "SK_DIM_PERSONA",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_PERSONA"
          },
          {
            "name": "INT_EDAD",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_EDAD"
          },
          {
            "name": "STR_CATEGORIA_EDAD",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_CATEGORIA_EDAD"
          },
          {
            "name": "CHR_SEXO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CHR_SEXO"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/VIVOBOOK-15\\SQLSERVER;DWH_COVID_19_COLOMBIA\",",
                "    dbo_TBL_DIM_PERSONA_T0 = Source{[Schema=\"dbo\",Item=\"TBL_DIM_PERSONA_T0\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_TBL_DIM_PERSONA_T0,{\"DT_FECHA_CARGUE\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Removed Columns\",{{\"STR_CATEGORIA_EDAD\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "PERSONA",
            "levels": [
              {
                "name": "Edad",
                "ordinal": 0,
                "column": "INT_EDAD"
              },
              {
                "name": "Categoría de Edad",
                "ordinal": 1,
                "column": "STR_CATEGORIA_EDAD"
              },
              {
                "name": "Sexo",
                "ordinal": 2,
                "column": "CHR_SEXO"
              }
            ]
          }
        ]
      },
      {
        "name": "TBL_DIM_TIEMPO_T0",
        "columns": [
          {
            "name": "SK_DIM_TIEMPO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_TIEMPO"
          },
          {
            "name": "DT_FECHA_NOTIFICACION",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DT_FECHA_NOTIFICACION"
          },
          {
            "name": "INT_DIA",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_DIA"
          },
          {
            "name": "INT_MES",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_MES"
          },
          {
            "name": "INT_ANIO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_ANIO"
          },
          {
            "name": "INT_PERIODO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_PERIODO"
          },
          {
            "name": "INT_SEMANA_MES",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_SEMANA_MES"
          },
          {
            "name": "STR_MES",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_MES"
          },
          {
            "name": "STR_SEMESTRE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_SEMESTRE"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/VIVOBOOK-15\\SQLSERVER;DWH_COVID_19_COLOMBIA\",",
                "    dbo_TBL_DIM_TIEMPO_T0 = Source{[Schema=\"dbo\",Item=\"TBL_DIM_TIEMPO_T0\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_TBL_DIM_TIEMPO_T0,{\"DT_FECHA_CARGUE\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Removed Columns\",{{\"STR_MES\", Text.Proper, type text}, {\"STR_SEMESTRE\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "TIEMPO",
            "levels": [
              {
                "name": "Fecha de Notificación",
                "ordinal": 0,
                "column": "DT_FECHA_NOTIFICACION"
              },
              {
                "name": "Número del Día",
                "ordinal": 1,
                "column": "INT_DIA"
              },
              {
                "name": "Número del Mes",
                "ordinal": 3,
                "column": "INT_MES"
              },
              {
                "name": "Número del Año",
                "ordinal": 7,
                "column": "INT_ANIO"
              },
              {
                "name": "Número del Periodo",
                "ordinal": 5,
                "column": "INT_PERIODO"
              },
              {
                "name": "Número de la Semana del Mes",
                "ordinal": 2,
                "column": "INT_SEMANA_MES"
              },
              {
                "name": "Nombre del Mes",
                "ordinal": 4,
                "column": "STR_MES"
              },
              {
                "name": "Nombre del Semestre",
                "ordinal": 6,
                "column": "STR_SEMESTRE"
              }
            ]
          }
        ]
      },
      {
        "name": "TBL_FACT_CASOS",
        "columns": [
          {
            "name": "SK_DIM_CASO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_CASO"
          },
          {
            "name": "SK_DIM_PERSONA",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_PERSONA"
          },
          {
            "name": "SK_DIM_UBICACION",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_UBICACION"
          },
          {
            "name": "SK_DIM_TIEMPO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_TIEMPO"
          },
          {
            "name": "BIT_RECUPERADO",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "BIT_RECUPERADO"
          },
          {
            "name": "BIT_MUERTO",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "BIT_MUERTO"
          },
          {
            "name": "INT_DIAS_REPORTE",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_DIAS_REPORTE"
          },
          {
            "name": "INT_DIAS_RETRASO_DIAGNOSTICO",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_DIAS_RETRASO_DIAGNOSTICO"
          },
          {
            "name": "INT_DIAS_RECUPERACION",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_DIAS_RECUPERACION"
          },
          {
            "name": "INT_DIAS_HASTA_MUERTE",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INT_DIAS_HASTA_MUERTE"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/VIVOBOOK-15\\SQLSERVER;DWH_COVID_19_COLOMBIA\",",
                "    dbo_TBL_FACT_CASOS = Source{[Schema=\"dbo\",Item=\"TBL_FACT_CASOS\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_TBL_FACT_CASOS,{\"DT_FECHA_CARGUE\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Promedio de Días de Duración de Reporte",
            "expression": "AVERAGE([INT_DIAS_REPORTE])",
            "formatString": "0.0",
            "displayFolder": "TIEMPO"
          },
          {
            "name": "Recuperados",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(TBL_FACT_CASOS),",
              "    TBL_FACT_CASOS[BIT_RECUPERADO] = TRUE()",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "CANTIDAD"
          },
          {
            "name": "Fallecidos",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(TBL_FACT_CASOS),",
              "    TBL_FACT_CASOS[BIT_MUERTO] = TRUE()",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "CANTIDAD"
          },
          {
            "name": "Promedio de Días de Retraso hasta Diagnóstico",
            "expression": "AVERAGE([INT_DIAS_RETRASO_DIAGNOSTICO])",
            "formatString": "0.0",
            "displayFolder": "TIEMPO"
          },
          {
            "name": "Promedio de Días hasta Recuperación",
            "expression": "AVERAGE([INT_DIAS_RECUPERACION])",
            "formatString": "0.0",
            "displayFolder": "TIEMPO"
          },
          {
            "name": "Promedio de Días Hasta Fallecer",
            "expression": "AVERAGE([INT_DIAS_HASTA_MUERTE])",
            "formatString": "0.0",
            "displayFolder": "TIEMPO"
          },
          {
            "name": "Total de Casos con ID",
            "expression": "COUNTA([SK_DIM_CASO])",
            "formatString": "#,##0",
            "displayFolder": "CANTIDAD"
          },
          {
            "name": "Total de Casos",
            "expression": "COUNTROWS(TBL_FACT_CASOS)",
            "formatString": "#,##0",
            "displayFolder": "CANTIDAD"
          },
          {
            "name": "Total de Casos sin ID",
            "expression": "COUNTROWS(TBL_FACT_CASOS)-COUNTA([SK_DIM_CASO])",
            "formatString": "#,##0",
            "displayFolder": "CANTIDAD"
          }
        ],
        "hierarchies": [
          {
            "name": "CASOS",
            "levels": [
              {
                "name": "Recuperado",
                "ordinal": 0,
                "column": "BIT_RECUPERADO"
              },
              {
                "name": "Fallecido",
                "ordinal": 1,
                "column": "BIT_MUERTO"
              },
              {
                "name": "Días de Duración de Reporte",
                "ordinal": 2,
                "column": "INT_DIAS_REPORTE"
              },
              {
                "name": "Días de Retraso hasta Diagnóstico",
                "ordinal": 3,
                "column": "INT_DIAS_RETRASO_DIAGNOSTICO"
              },
              {
                "name": "Días hasta Recuperación",
                "ordinal": 4,
                "column": "INT_DIAS_RECUPERACION"
              },
              {
                "name": "Días hasta Fallecer",
                "ordinal": 5,
                "column": "INT_DIAS_HASTA_MUERTE"
              }
            ]
          }
        ]
      },
      {
        "name": "TBL_DIM_UBICACION_T0",
        "columns": [
          {
            "name": "SK_DIM_UBICACION",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SK_DIM_UBICACION"
          },
          {
            "name": "STR_DEPARTAMENTO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_DEPARTAMENTO"
          },
          {
            "name": "STR_MUNICIPIO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_MUNICIPIO"
          },
          {
            "name": "STR_UBICACION_DEPARTAMENTO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_UBICACION_DEPARTAMENTO"
          },
          {
            "name": "STR_UBICACION_MUNICIPIO",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STR_UBICACION_MUNICIPIO"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/VIVOBOOK-15\\SQLSERVER;DWH_COVID_19_COLOMBIA\",",
                "    dbo_TBL_DIM_UBICACION_T0 = Source{[Schema=\"dbo\",Item=\"TBL_DIM_UBICACION_T0\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_TBL_DIM_UBICACION_T0,{\"DT_FECHA_CARGUE\"}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Removed Columns\",{{\"STR_DEPARTAMENTO\", Text.Proper, type text}, {\"STR_MUNICIPIO\", Text.Proper, type text}, {\"STR_UBICACION_DEPARTAMENTO\", Text.Proper, type text}, {\"STR_UBICACION_MUNICIPIO\", Text.Proper, type text}})",
                "in",
                "    #\"Capitalized Each Word\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "UBICACIÓN",
            "levels": [
              {
                "name": "Ubicación del Departamento",
                "ordinal": 2,
                "column": "STR_UBICACION_DEPARTAMENTO"
              },
              {
                "name": "Ubicación del Municipio",
                "ordinal": 3,
                "column": "STR_UBICACION_MUNICIPIO"
              },
              {
                "name": "Municipio",
                "ordinal": 1,
                "column": "STR_MUNICIPIO"
              },
              {
                "name": "Departamento",
                "ordinal": 0,
                "column": "STR_DEPARTAMENTO"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "14542611-0ade-45a4-bf2e-4b491b48fa1a",
        "fromTable": "TBL_FACT_CASOS",
        "fromColumn": "SK_DIM_CASO",
        "toTable": "TBL_DIM_CASO_T2",
        "toColumn": "SK_DIM_CASO"
      },
      {
        "name": "b93a6a31-aef7-4de0-9c79-86df06fb04ae",
        "fromTable": "TBL_FACT_CASOS",
        "fromColumn": "SK_DIM_PERSONA",
        "toTable": "TBL_DIM_PERSONA_T0",
        "toColumn": "SK_DIM_PERSONA"
      },
      {
        "name": "cfee81fa-d6ac-49ed-8482-e912ccf8f9aa",
        "fromTable": "TBL_FACT_CASOS",
        "fromColumn": "SK_DIM_TIEMPO",
        "toTable": "TBL_DIM_TIEMPO_T0",
        "toColumn": "SK_DIM_TIEMPO"
      },
      {
        "name": "bc68ecbc-989c-4755-92cc-833789fc77d8",
        "fromTable": "TBL_FACT_CASOS",
        "fromColumn": "SK_DIM_UBICACION",
        "toTable": "TBL_DIM_UBICACION_T0",
        "toColumn": "SK_DIM_UBICACION"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}